// Package sandforge (module root) embeds the deploy assets + the reference PRD so the compiled
// binary is fully self-contained: an end user installs ONE binary and never needs this repo.
//
// The assets are embedded as a single gzipped tarball (assets/deploy.tar.gz), regenerated by
// `mage genAssets` (also wired into `mage build`). A tarball — rather than `//go:embed all:deploy`
// — is deliberate: go:embed silently drops nested-module subtrees (deploy/tasks-app/backend has
// its own go.mod) and errors on the symlinks npm leaves behind. A tar sidesteps every one of
// those quirks. At runtime the tarball is extracted once to a content-addressed directory under
// ~/.sandforge and used as the "repo root" the rest of the CLI expects (deploy/ + docs/prd.md).
package sandforge

import (
	"archive/tar"
	"bytes"
	"compress/gzip"
	"crypto/sha256"
	_ "embed"
	"encoding/hex"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
	"time"
)

//go:embed assets/deploy.tar.gz
var assetsTarGz []byte

// AgentsDoc is the local-agents user guide (docs/agents.md), embedded so the agents UI can render
// it in-app (its Docs tab) even when run from the standalone binary with no source tree on disk.
//
//go:embed docs/agents.md
var AgentsDoc string

// assetsHash is the digest of the embedded tarball; it keys the materialized directory so a new
// binary (changed compose file, workflow, etc.) re-materializes instead of reusing stale assets.
func assetsHash() string {
	sum := sha256.Sum256(assetsTarGz)
	return hex.EncodeToString(sum[:])[:16]
}

// Materialize extracts the embedded assets into a content-addressed directory under baseDir
// (typically ~/.sandforge) and returns that directory — the "repo root" with deploy/ + docs/.
// Idempotent: a completed prior extraction (same hash) is reused; a partial one is redone, so we
// never run against half-written assets.
func Materialize(baseDir string) (string, error) {
	if len(assetsTarGz) == 0 {
		return "", fmt.Errorf("embedded assets are empty — the binary was built without assets/deploy.tar.gz (run `mage genAssets`)")
	}
	hash := assetsHash()
	parent := filepath.Join(baseDir, "assets")
	dir := filepath.Join(parent, hash)
	// Reuse only a COMPLETE extraction: sentinel present AND a load-bearing file still there (guards
	// against a dir later half-deleted by a tmp reaper — we re-materialize rather than fail later).
	if materializedComplete(dir) {
		return dir, nil
	}
	if err := os.MkdirAll(parent, 0o755); err != nil {
		return "", err
	}
	// Extract into a unique temp dir, then atomically rename into place. Two concurrent first-runs
	// no longer corrupt each other's extraction (the TOCTOU that RemoveAll-then-extract allowed).
	tmp, err := os.MkdirTemp(parent, "."+hash+".tmp-")
	if err != nil {
		return "", err
	}
	defer os.RemoveAll(tmp) // no-op once renamed away
	if err := extractTarGz(assetsTarGz, tmp); err != nil {
		return "", fmt.Errorf("extract embedded assets: %w", err)
	}
	// Guard (no silent failure): the load-bearing pieces must have survived. The nested-module
	// backend and the CI workflow are exactly what naive go:embed dropped.
	for _, must := range loadBearingAssets {
		if _, err := os.Stat(filepath.Join(tmp, must)); err != nil {
			return "", fmt.Errorf("embedded tarball is incomplete (missing %s)", must)
		}
	}
	if err := os.WriteFile(filepath.Join(tmp, ".materialized"), []byte(hash), 0o644); err != nil {
		return "", err
	}
	// Atomic publish. If the rename fails, something is already at `dir`: adopt it ONLY if it is a
	// complete extraction (another process won the race); if it's a corrupt/partial leftover,
	// replace it with our freshly-extracted, verified tree rather than returning broken assets.
	if err := os.Rename(tmp, dir); err != nil {
		if materializedComplete(dir) {
			return dir, nil
		}
		if rmErr := os.RemoveAll(dir); rmErr != nil {
			return "", fmt.Errorf("replace incomplete materialized assets at %s: %w", dir, rmErr)
		}
		if err2 := os.Rename(tmp, dir); err2 != nil {
			if materializedComplete(dir) { // lost a second race to a good writer — fine
				return dir, nil
			}
			return "", fmt.Errorf("publish materialized assets: %w", err2)
		}
	}
	pruneTempAssets(parent)
	return dir, nil
}

// loadBearingAssets are the files that MUST be present for a materialized tree to be usable. They
// are the exact set verified on extraction; reusing a cache that lacks any of them would fail
// downstream (e.g. a missing compose or PRD file), so completeness checks the whole set.
var loadBearingAssets = []string{
	filepath.Join("deploy", "tasks-app", "backend", "main.go"),
	filepath.Join("deploy", "tasks-app", ".github", "workflows", "ci.yml"),
	filepath.Join("deploy", "control-plane", "control-plane.compose.yml"),
	filepath.Join("docs", "prd.md"),
}

// materializedComplete reports whether dir holds a fully-extracted asset tree: the sentinel plus
// EVERY load-bearing file (not just one) — so a partially-deleted cache dir is treated as
// incomplete and re-materialized, honoring Materialize's "a partial one is redone" contract.
func materializedComplete(dir string) bool {
	if _, err := os.Stat(filepath.Join(dir, ".materialized")); err != nil {
		return false
	}
	for _, must := range loadBearingAssets {
		if _, err := os.Stat(filepath.Join(dir, must)); err != nil {
			return false
		}
	}
	return true
}

// pruneTempAssets removes only orphaned temp extraction dirs left by a crashed/abandoned
// Materialize (names contain ".tmp-"). It deliberately does NOT delete complete sibling version
// dirs: another sandforge process — built from a different binary version — may be actively using
// its own materialized assets (compose files, verify.sh), and deleting them mid-run would break it
// (the concurrency hazard Copilot flagged). Stale complete versions are a small, bounded disk cost;
// correctness wins. Best-effort.
func pruneTempAssets(parent string) {
	entries, err := os.ReadDir(parent)
	if err != nil {
		return
	}
	cutoff := time.Now().Add(-time.Hour)
	for _, e := range entries {
		if !e.IsDir() || !strings.Contains(e.Name(), ".tmp-") {
			continue
		}
		// Only remove ORPHANED temp dirs (older than an hour) — never an in-flight extraction from
		// a CONCURRENT process, which would break its materialize mid-flight. A real extraction
		// takes well under a second, so an hour-old temp dir is unambiguously a crash leftover.
		if info, err := e.Info(); err == nil && info.ModTime().Before(cutoff) {
			os.RemoveAll(filepath.Join(parent, e.Name()))
		}
	}
}

// extractTarGz safely unpacks a gzipped tar into dir, rejecting path traversal.
func extractTarGz(data []byte, dir string) error {
	gz, err := gzip.NewReader(bytes.NewReader(data))
	if err != nil {
		return err
	}
	defer gz.Close()
	tr := tar.NewReader(gz)
	for {
		hdr, err := tr.Next()
		if err == io.EOF {
			break
		}
		if err != nil {
			return err
		}
		// Reject absolute paths and traversal.
		clean := filepath.Clean(hdr.Name)
		if filepath.IsAbs(clean) || strings.HasPrefix(clean, ".."+string(os.PathSeparator)) || clean == ".." {
			return fmt.Errorf("unsafe path in asset tarball: %q", hdr.Name)
		}
		target := filepath.Join(dir, clean)
		switch hdr.Typeflag {
		case tar.TypeDir:
			if err := os.MkdirAll(target, 0o755); err != nil {
				return err
			}
		case tar.TypeReg:
			if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
				return err
			}
			f, err := os.OpenFile(target, os.O_CREATE|os.O_TRUNC|os.O_WRONLY, os.FileMode(hdr.Mode)&0o777)
			if err != nil {
				return err
			}
			if _, err := io.Copy(f, tr); err != nil {
				f.Close()
				return err
			}
			if err := f.Close(); err != nil {
				return err
			}
		default:
			// Fail loud on anything that isn't a regular file or dir (symlink/device/etc.). The
			// generated tarball only contains regular files, so an unsupported entry means a
			// corrupt/tampered tarball — don't silently produce an incomplete asset tree.
			return fmt.Errorf("unsupported entry %q (tar type %d) in asset tarball", hdr.Name, hdr.Typeflag)
		}
	}
	return nil
}
