#!/usr/bin/env bash
# Render the documentation diagrams: SVG sources -> PNG.
#
# Sources of truth are the hand-authored *.svg files in docs/diagrams/.
# The committed *.png files next to them are generated by this script and are
# what the Markdown docs embed (GitHub renders PNG reliably; inline SVG less so).
#
# Pipeline: rsvg-convert (librsvg) rasterizes each SVG at 2x for crisp output.
#   brew install librsvg            # provides rsvg-convert
#
# Fonts: the SVGs use the "Helvetica Neue" / Helvetica family (clean Apple
# typography, not a hand-drawn style). librsvg resolves these via fontconfig;
# on macOS they ship with the OS. On Linux CI install a Helvetica-compatible
# face (e.g. fonts-liberation) or the output font will substitute.
set -euo pipefail

cd "$(dirname "$0")/.."
DIR="docs/diagrams"
SCALE="${SCALE:-2}"

command -v rsvg-convert >/dev/null 2>&1 || {
  echo "error: rsvg-convert not found. Install librsvg (brew install librsvg)." >&2
  exit 1
}

shopt -s nullglob
svgs=("$DIR"/*.svg)
[ ${#svgs[@]} -gt 0 ] || { echo "error: no SVGs in $DIR" >&2; exit 1; }

for svg in "${svgs[@]}"; do
  png="${svg%.svg}.png"
  rsvg-convert -z "$SCALE" "$svg" -o "$png"
  echo "rendered $png"
done
